from io import BytesIO

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors


# ==========================================================
# PDF REPORT
# ==========================================================

def create_pdf_report(
    ats_score,
    rating,
    found_skills,
    missing_skills,
    feedback,
    strength,
    completeness,
    roles
):
    """
    Generate Resume Report PDF and return BytesIO buffer
    """

    buffer = BytesIO()

    styles = getSampleStyleSheet()

    pdf = SimpleDocTemplate(buffer)

    story = []

    # ======================================================
    # TITLE
    # ======================================================

    story.append(
        Paragraph(
            "<b>AI Resume Analyzer Report</b>",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 20))

    # ======================================================
    # ATS TABLE
    # ======================================================

    table_data = [

        ["ATS Score", f"{ats_score}%"],

        ["Rating", rating],

        ["Resume Strength", f"{strength}/100"],

        ["Resume Completeness", f"{completeness}%"]

    ]

    table = Table(table_data, colWidths=[180, 250])

    table.setStyle(

        TableStyle([

            ("BACKGROUND", (0,0), (-1,0), colors.lightblue),

            ("GRID", (0,0), (-1,-1), 1, colors.black),

            ("BACKGROUND", (0,1), (0,-1), colors.whitesmoke),

            ("FONTNAME", (0,0), (-1,-1), "Helvetica-Bold"),

            ("BOTTOMPADDING", (0,0), (-1,-1), 8),

            ("TOPPADDING", (0,0), (-1,-1), 8)

        ])

    )

    story.append(table)

    story.append(Spacer(1, 20))
        # ======================================================
    # DETECTED SKILLS
    # ======================================================

    story.append(
        Paragraph(
            "<b>Detected Skills</b>",
            styles["Heading2"]
        )
    )

    if found_skills:

        for skill in found_skills:

            story.append(
                Paragraph(
                    f"• {skill}",
                    styles["BodyText"]
                )
            )

    else:

        story.append(
            Paragraph(
                "No skills detected.",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 20))

    # ======================================================
    # MISSING SKILLS
    # ======================================================

    story.append(
        Paragraph(
            "<b>Missing Skills</b>",
            styles["Heading2"]
        )
    )

    if missing_skills:

        for skill in missing_skills:

            story.append(
                Paragraph(
                    f"• {skill}",
                    styles["BodyText"]
                )
            )

    else:

        story.append(
            Paragraph(
                "No Missing Skills 🎉",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 20))

    # ======================================================
    # RECOMMENDED ROLES
    # ======================================================

    story.append(
        Paragraph(
            "<b>Recommended Career Roles</b>",
            styles["Heading2"]
        )
    )

    if roles:

        for role in roles:

            story.append(
                Paragraph(
                    f"• {role}",
                    styles["BodyText"]
                )
            )

    else:

        story.append(
            Paragraph(
                "No recommendations available.",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 20))
        # ======================================================
    # AI FEEDBACK
    # ======================================================

    story.append(
        Paragraph(
            "<b>AI Feedback</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            feedback.replace("\n", "<br/>"),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 20))

    # ======================================================
    # FOOTER
    # ======================================================

    story.append(
        Paragraph(
            "Generated by <b>AI Resume Analyzer Pro</b>",
            styles["Italic"]
        )
    )

    story.append(
        Paragraph(
            "Thank you for using AI Resume Analyzer Pro.",
            styles["BodyText"]
        )
    )

    # ======================================================
    # BUILD PDF
    # ======================================================

    pdf.build(story)

    buffer.seek(0)

    return buffer
