from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet


# ==========================================================
# PDF REPORT
# ==========================================================

def create_pdf_report(

        filename,

        ats_score,

        rating,

        found_skills,

        missing_skills,

        feedback,

        strength,

        completeness,

        roles

):

    styles = getSampleStyleSheet()

    pdf = SimpleDocTemplate(filename)

    story = []

    # --------------------------------------------
    # TITLE
    # --------------------------------------------

    story.append(
        Paragraph(
            "<b>AI Resume Analyzer Report</b>",
            styles["Title"]
        )
    )

    story.append(Spacer(1,20))

    # --------------------------------------------
    # ATS
    # --------------------------------------------

    story.append(
        Paragraph(
            f"<b>ATS Score :</b> {ats_score}%",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Rating :</b> {rating}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,15))

    # --------------------------------------------
    # Resume Quality
    # --------------------------------------------

    story.append(
        Paragraph(
            f"<b>Resume Strength :</b> {strength}/100",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Resume Completeness :</b> {completeness}%",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,15))

    # --------------------------------------------
    # Skills
    # --------------------------------------------

    story.append(
        Paragraph(
            "<b>Detected Skills</b>",
            styles["Heading2"]
        )
    )

    for skill in found_skills:

        story.append(
            Paragraph(
                f"• {skill}",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1,15))

    # --------------------------------------------
    # Missing Skills
    # --------------------------------------------

    story.append(
        Paragraph(
            "<b>Missing Skills</b>",
            styles["Heading2"]
        )
    )

    if missing_skills:

        for skill in missing_skills:

            story.append(
                Paragraph(
                    f"• {skill}",
                    styles["BodyText"]
                )
            )

    else:

        story.append(
            Paragraph(
                "No Missing Skills",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1,15))

    # --------------------------------------------
    # Career Roles
    # --------------------------------------------

    story.append(
        Paragraph(
            "<b>Recommended Roles</b>",
            styles["Heading2"]
        )
    )

    for role in roles:

        story.append(
            Paragraph(
                f"• {role}",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1,15))

    # --------------------------------------------
    # Feedback
    # --------------------------------------------

    story.append(
        Paragraph(
            "<b>AI Feedback</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            feedback.replace("\n","<br/>"),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,20))

    # --------------------------------------------
    # Footer
    # --------------------------------------------

    story.append(
        Paragraph(
            "Generated by AI Resume Analyzer Pro",
            styles["Italic"]
        )
    )

    pdf.build(story)