"""
report.py
-----------------------------------
PDF Report Generator
"""

from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

styles = getSampleStyleSheet()

# ==========================================================
# CREATE PDF REPORT
# ==========================================================

def create_pdf_report(

    resume_text,

    ats_score,

    skills,

    missing_skills,

    feedback

):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    story = []

    # ======================================================
    # TITLE
    # ======================================================

    story.append(

        Paragraph(
            "<b>AI Resume Analyzer Report</b>",
            styles["Title"]
        )

    )

    story.append(
        Spacer(1,20)
    )

    # ======================================================
    # ATS SCORE
    # ======================================================

    story.append(

        Paragraph(
            f"<b>ATS Score :</b> {ats_score}%",
            styles["Heading2"]
        )

    )

    story.append(
        Spacer(1,15)
    )

    # ======================================================
    # DETECTED SKILLS
    # ======================================================

    story.append(

        Paragraph(
            "<b>Detected Skills</b>",
            styles["Heading2"]
        )

    )

    for skill in skills:

        story.append(

            Paragraph(
                f"• {skill}",
                styles["BodyText"]
            )

        )

    story.append(
        Spacer(1,15)
    )

    # ======================================================
    # MISSING SKILLS
    # ======================================================

    story.append(

        Paragraph(
            "<b>Missing Skills</b>",
            styles["Heading2"]
        )

    )

    for skill in missing_skills:

        story.append(

            Paragraph(
                f"• {skill}",
                styles["BodyText"]
            )

        )

    story.append(
        Spacer(1,15)
    )
        # ======================================================
    # FEEDBACK
    # ======================================================

    story.append(
        Paragraph(
            "<b>Resume Feedback</b>",
            styles["Heading2"]
        )
    )

    if feedback:

        for item in feedback:

            story.append(
                Paragraph(
                    f"• {item}",
                    styles["BodyText"]
                )
            )

    else:

        story.append(
            Paragraph(
                "No feedback available.",
                styles["BodyText"]
            )
        )

    story.append(
        Spacer(1, 15)
    )

    # ======================================================
    # RESUME PREVIEW
    # ======================================================

    story.append(
        Paragraph(
            "<b>Resume Preview</b>",
            styles["Heading2"]
        )
    )

    preview = resume_text[:1200]

    story.append(
        Paragraph(
            preview.replace("\n", "<br/>"),
            styles["BodyText"]
        )
    )

    story.append(
        Spacer(1, 20)
    )

    # ======================================================
    # SUMMARY
    # ======================================================

    story.append(
        Paragraph(
            "<b>Summary</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"""
            ATS Score : {ats_score}%<br/>
            Skills Found : {len(skills)}<br/>
            Missing Skills : {len(missing_skills)}
            """,
            styles["BodyText"]
        )
    )

    story.append(
        Spacer(1, 20)
    )

    # ======================================================
    # FOOTER
    # ======================================================

    story.append(
        Paragraph(
            "<b>Generated by AI Resume Analyzer</b>",
            styles["Heading3"]
        )
    )

    story.append(
        Paragraph(
            "Developed by Vaishnavi Goyal",
            styles["BodyText"]
        )
    )

    # ======================================================
    # BUILD PDF
    # ======================================================

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf
